### ISSUE TITLE
Mac OS installer leaves system unbootable

### ISSUE THREAD

**Issue by lm1baker** [thozza/dnssec-trigger#1]
I tried to install dns-sec trigger using the dnssectrigger-0.13.dmg package from https://www.nlnetlabs.nl/projects/dnssec-trigger/, but upon install completion I started receiving system errors. Upon reboot, the system would not even start except for recovery and single-user modes. Long story short, the /var/ directory (which is a symlink to /private/var) had been overwritten and only by restoring the symlink could I have the system boot. 

My operating system version is MacOSX Yosemite 10.10.5 (14F2511), it's on an old (2009) macbook so, except for being upgraded from snow leopard, as far as I know there is nothing special about the install.

**Comment by thozza** [comment]
Hello.
This is not an official code repository for dnssec-trigger project. Please report any issues using the upstream mailing list - https://open.nlnetlabs.nl/mailman/listinfo/dnssec-trigger
